apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: yugabyte
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - flask-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flask-api
        image: europe-west1-docker.pkg.dev/ddis-course/vishnurepo/flask-api:v8
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://yugabyte:yugabyte@yb-tservers.yugabyte.svc.cluster.local:5433/yugabyte"
        - name: SECRET_KEY
          value: "your-production-secret-key-here"
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"