apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: yugabyte
spec:
  selector:
    app: flask-api  # Must match your deployment's pod labels
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8080  # Must match your containerPort
  type: LoadBalancer